### ISSUE TITLE
File Sharing (Backend)

### ISSUE THREAD

**Issue by petribayley** [Group4-3/ESSW#28]

**Comment by techno156** [comment]
How are we going to implement this?

Are files going to be stored on within the database, or are they going to be stored on the local file system, with a corresponding entry in the database, containing the relevant metadata?

Do they need to be stored in such a way that the files are obfuscated from viewing by users running on the same container?

**Comment by techno156** [comment]
The way that I was thinking the file sharing could work is that we have a relational table, with a foreign key set up, attached to the secret database, that contains the original file name, attached by foreign key to the secret. The foreign key would be set up to self-delete if the parent secret is removed, so we don't need to purge the file database, except to check for orphaned records.

The files would be renamed on-disk to the corresponding file checksum (CRC32?), with the original name stored inside the database. On retrieval, the file will be decrypted, its name changed back to the original, and presented for downloading.
The only issues that come to mind immediately is how to make sure that the secret, and relevant files aren't deleted until -after- downloading
The easiest way that I could think of is that instead of deleting immediately, we have an additional column to turn off secret visibility, or set the expiry of the secret to then on viewing, which puts it on the purge list, and should prevent it from being displayed after that point
That would give the user time to download the file until the purge executes.

(Copied from Discord)

**Comment by techno156** [comment]
Front and end backend changes can all be applied to this branch
