### ISSUE TITLE
Shell scripts not being found

### ISSUE THREAD

**Issue by petribayley** [Group4-3/ESSW#53]
/docker-entrypoint.sh: 22: /docker-entrypoint.d/nginx_noncertbot_gen.sh: not found

I've noticed this error and it occurs when the nginx_noncertbot_gen.sh file is saved with windows style file ending rather than UNIX style which is leading the nginx being unable to execute the script. My proposal is to create a github test that will check for file endings to force UNIX style as this is deploying in an environment using UNIX ending.

**Comment by techno156** [comment]
Rather than needing to create a specific github test, it is possible to change the repository's line ending settings, and configure them to use the unix-specific version, as opposed to windows only.

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by petribayley** [comment]
> Rather than needing to create a specific github test, it is possible to change the repository's line ending settings, and configure them to use the unix-specific version, as opposed to windows only.
> 
> https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

Good catch, that's definitely a good idea
